// javascript_react/src/components/contractor_directory/contractor_directory.js
import React, { useContext, useState } from 'react'
import Popup from 'reactjs-popup';
import { toast } from 'react-toastify';
import 'reactjs-popup/dist/index.css';

import CompensationEditor from "../compensation_editor/compensation_editor";
import FlexileButton from '../flexile_button/flexile_button';
import { ActiveContractorContext } from '../../utils/ActiveContractorContext';
import './contractor_directory.css';
import '../popup.css';

function ContractorDirectory(props) {
  const [contractors, setContractors] = useState([...props.contractors])
  const {activeContractorInfo, setActiveContractorInfo} = useContext(ActiveContractorContext)

  const updateContractorData = (new_contractor_data) => {
    const new_contractors = [...props.contractors];
    const contractor_at_idx = {...new_contractors[activeContractorInfo.idx]};
    contractor_at_idx.hourly_rate = new_contractor_data.hourly_rate;
    contractor_at_idx.hours_per_week = new_contractor_data.hours_per_week;
    contractor_at_idx.weeks_per_year = new_contractor_data.weeks_per_year;
    contractor_at_idx.stock_options_percentage = new_contractor_data.stock_options_percentage;
    new_contractors[activeContractorInfo.idx] = contractor_at_idx;
    setContractors(new_contractors);

    setActiveContractorInfo(null)
    toast.success(
      "Successfully updated copmensation for " + contractor_at_idx.full_name,
      { position: toast.POSITION.BOTTOM_CENTER });
  }

  return (
  <div className="table-container">
    <div className="table">
      <div className="row header">
        <div className="cell">Full Name</div>
        <div className="cell">Role</div>
        <div className="cell">Location</div>
        <div className="cell">Joined On</div>
        <div className="cell">$/hr</div>
        <div className="cell">Hours/wk</div>
        <div className="cell">Weeks/yr</div>
        <div className="cell">Stock %</div>
        <div className="cell">Action</div>
      </div>
      {contractors.map((contractor, idx) => {
        return <div className="row table-body-row" key={idx}>
          <div className="cell" data-title="Full Name">
            {contractor.full_name}
          </div>
          <div className="cell" data-title="Role">
            {contractor.role}
          </div>
          <div className="cell" data-title="Location">
            {contractor.location}
          </div>
          <div className="cell" data-title="Joined On">
            {contractor.joined_on}
          </div>
          <div className="cell" data-title="Hourly Rate">
            {contractor.hourly_rate}
          </div>
          <div className="cell" data-title="Hours Per Week">
            {contractor.hours_per_week}
          </div>
          <div className="cell" data-title="Weeks Per Year">
            {contractor.weeks_per_year}
          </div>
          <div className="cell" data-title="Stock %">
            {contractor.stock_options_percentage}%
          </div>
          <div className="cell" data-title="Action">
            <FlexileButton text="Edit" onClick={() => setActiveContractorInfo({contractor, idx})} />
          </div>
        </div>
      })}
    </div>
    {activeContractorInfo?.contractor && <Popup
      open={activeContractorInfo}
      closeOnDocumentClick
      onClose={() => setActiveContractorInfo(null)}
      modal>
        {close => (
          <CompensationEditor
          contractor={activeContractorInfo.contractor}
          close={close}
          onSubmit={updateContractorData} />
        )}
    </Popup>}
  </div>
  )
}

export default ContractorDirectory

// javascript_vue/src/components/ContractorDirectory.vue
<script setup lang="ts">
import FlexileButton from "@/components/FlexileButton.vue";
import { contractor_data } from "../utils/data";
</script>

<template>
  <div class="table-container">
    <div class="table">
      <div class="row header">
        <div class="cell">Full Name</div>
        <div class="cell">Role</div>
        <div class="cell">Location</div>
        <div class="cell">Joined On</div>
        <div class="cell">$/hr</div>
        <div class="cell">Hours/wk</div>
        <div class="cell">Weeks/yr</div>
        <div class="cell">Stock %</div>
        <div class="cell">Action</div>
      </div>
      <div v-for="contractor in contractor_data" :key="contractor.id" class="row table-body-row">
        <div class="cell" data-title="Full Name">
          {{contractor.full_name}}
        </div>
        <div class="cell" data-title="Role">
          {{contractor.role}}
        </div>
        <div class="cell" data-title="Location">
          {{contractor.location}}
        </div>
        <div class="cell" data-title="Joined On">
          {{contractor.joined_on}}
        </div>
        <div class="cell" data-title="Hourly Rate">
          {{contractor.hourly_rate}}
        </div>
        <div class="cell" data-title="Hours Per Week">
          {{contractor.hours_per_week}}
        </div>
        <div class="cell" data-title="Weeks Per Year">
          {{contractor.weeks_per_year}}
        </div>
        <div class="cell" data-title="Stock %">
          {{contractor.stock_options_percentage}}%
        </div>
        <div class="cell" data-title="Action">
          <FlexileButton />
        </div>
      </div>
    </div>
    <!-- {activeContractorInfo?.contractor && <Popup
      open={activeContractorInfo}
      closeOnDocumentClick
      onClose={() => setActiveContractorInfo(null)}
      modal>
        {close => (
          <CompensationEditor
          contractor={activeContractorInfo.contractor}
          close={close}
          onSubmit={updateContractorData} />
        )}
    </Popup>} -->
  </div>
</template>

<style scoped>
.table-container {
  width: 960px;
  border-radius: 10px;
  overflow: hidden
}

.table {
  width: 100%;
  display: table;
  margin: 0
}

@media screen and (max-width: 768px) {
  .table {
      display:block
  }
}

.row {
  display: table-row;
  background: #fff
}

.row.header {
  color: #fff;
  background: black
}

@media screen and (max-width: 768px) {
  .row {
      display:block
  }

  .row.header {
      padding: 0;
      height: 0
  }

  .row.header .cell {
      display: none
  }

  .row .cell:before {
      font-size: 12px;
      color: gray;
      line-height: 1.2;
      text-transform: uppercase;
      font-weight: unset!important;
      margin-bottom: 13px;
      content: attr(data-title);
      min-width: 98px;
      display: block
  }
}

.cell {
  display: table-cell
}

@media screen and (max-width: 768px) {
  .cell {
      display:block
  }
}

.row .cell {
  font-size: 15px;
  color: #666;
  line-height: 1.2;
  font-weight: unset!important;
  padding-top: 20px;
  padding-bottom: 20px;
  border-bottom: 1px solid #f2f2f2
}

.row.header .cell {
  font-size: 18px;
  color: #fff;
  line-height: 1.2;
  font-weight: unset!important;
  padding-top: 19px;
  padding-bottom: 19px
}

.row .cell:nth-child(1) {
  width: 150px;
}

.row .cell:nth-child(9) {
  width: 150px;
}

.table-body-row:hover {
  background-color: #ececff;
}

@media(max-width: 768px) {
  .row {
      border-bottom:1px solid #f2f2f2;
      padding-bottom: 18px;
      padding-top: 30px;
      padding-right: 15px;
      margin: 0
  }

  .row .cell {
      border: none;
      padding-left: 30px;
      padding-top: 16px;
      padding-bottom: 16px
  }

  .row .cell:nth-child(1) {
      padding-left: 30px
  }

  .row .cell {
      font-size: 18px;
      color: #555;
      line-height: 1.2;
      font-weight: unset!important
  }

  .table,.row,.cell {
      width: 100%!important
  }
}
</style>
